<?php

namespace Database\Seeders;

use App\Models\Subject;
use Illuminate\Database\Seeder;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $subjects = [
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '07:00:00',
                'end_time' => '07:50:00',
            ],

            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '07:50:00',
                'end_time' => '08:40:00',
            ],

            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '08:40:00',
                'end_time' => '09:30:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '08:40:00',
                'end_time' => '09:30:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '08:40:00',
                'end_time' => '09:30:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '08:40:00',
                'end_time' => '09:30:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '08:40:00',
                'end_time' => '09:30:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Sabado',
                'start_time' => '08:40:00',
                'end_time' => '09:30:00',
            ],

            [
                'subject_type_id' => 3,
                'capacity' => 20,
                'day' => 'Lunes',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 5,
                'day' => 'Lunes',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 3,
                'capacity' => 20,
                'day' => 'Martes',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 5,
                'day' => 'Martes',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 3,
                'capacity' => 20,
                'day' => 'Miercoles',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 5,
                'day' => 'Miercoles',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 3,
                'capacity' => 20,
                'day' => 'Jueves',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 5,
                'day' => 'Jueves',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 3,
                'capacity' => 20,
                'day' => 'Viernes',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 5,
                'day' => 'Viernes',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],
            [
                'subject_type_id' => 4,
                'capacity' => 20,
                'day' => 'Sabado',
                'start_time' => '09:30:00',
                'end_time' => '10:20:00',
            ],

            [
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '10:20:00',
                'end_time' => '11:10:00',
            ],
            [ 
                'subject_type_id' => 2,
                'capacity' => 5,
                'day' => 'Lunes',
                'start_time' => '10:20:00',
                'end_time' => '11:10:00',
            ],
            [ 
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '10:20:00',
                'end_time' => '11:10:00',
            ],
            [   
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '10:20:00',
                'end_time' => '11:10:00',
            ],
            [ 
                'subject_type_id' => 2,
                'capacity' => 5,
                'day' => 'Miercoles',
                'start_time' => '10:20:00',
                'end_time' => '11:10:00',
            ],
            [ 
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '10:20:00',
                'end_time' => '11:10:00',
            ],
            [ 
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '10:20:00',
                'end_time' => '11:10:00',
            ],
            [ 
                'subject_type_id' => 4,
                'capacity' => 20,
                'day' => 'Sabado',
                'start_time' => '10:20:00',
                'end_time' => '11:10:00',
            ],

            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Lunes',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Martes',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Miercoles',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Jueves',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Viernes',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],
            [
                'subject_type_id' => 5,
                'capacity' => 20,
                'day' => 'Sabado',
                'start_time' => '11:10:00',
                'end_time' => '12:00:00',
            ],

            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Lunes',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],
            [
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Martes',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Miercoles',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],
            [
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Jueves',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Viernes',
                'start_time' => '12:00:00',
                'end_time' => '12:50:00',
            ],

            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Lunes',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Martes',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Miercoles',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Jueves',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Viernes',
                'start_time' => '12:50:00',
                'end_time' => '13:40:00',
            ],
            
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Lunes',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Martes',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Miercoles',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Jueves',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Viernes',
                'start_time' => '13:40:00',
                'end_time' => '14:30:00',
            ],

            [   
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Lunes',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],
            [   
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Martes',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],
            [   
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Miercoles',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],
            [   
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Jueves',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],
            [   
                'subject_type_id' => 3,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Viernes',
                'start_time' => '14:30:00',
                'end_time' => '15:20:00',
            ],

            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Lunes',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Martes',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Miercoles',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Jueves',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],
            [   
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 5,
                'day' => 'Viernes',
                'start_time' => '15:20:00',
                'end_time' => '16:10:00',
            ],

            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Miercoles',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Miercoles',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Miercoles',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '16:10:00',
                'end_time' => '17:00:00',
            ],

            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Miercoles',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Miercoles',
               'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Miercoles',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '17:00:00',
                'end_time' => '17:50:00',
            ],

            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Lunes',
               'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Martes',
               'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Miercoles',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Miercoles',
               'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Miercoles',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '17:50:00',
                'end_time' => '18:40:00',
            ],

            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Lunes',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Lunes',
               'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Martes',
              'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Martes',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Miercoles',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Miercoles',
               'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Miercoles',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Jueves',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 6,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 7,
                'capacity' => 7,
                'day' => 'Viernes',
                'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],
            [   
                'subject_type_id' => 8,
                'capacity' => 7,
                'day' => 'Viernes',
               'start_time' => '18:40:00',
                'end_time' => '19:30:00',
            ],

            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '19:30:00',
                'end_time' => '20:20:00',
            ],

            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
               'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Martes',
               'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '20:20:00',
                'end_time' => '21:10:00',
            ],

             [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Lunes',
                'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Lunes',
               'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Martes',
               'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Martes',
                'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Miercoles',
                'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Jueves',
                'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ],
            [
                'subject_type_id' => 1,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ],
            [
                'subject_type_id' => 2,
                'capacity' => 15,
                'day' => 'Viernes',
                'start_time' => '21:10:00',
                'end_time' => '22:00:00',
            ]
        ];

        foreach ($subjects as $subject) {
            Subject::create($subject);
        }
    }
}